[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.69.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/components"
  to = "/docs/#whats-powering-tinkerbell"
  status = 301

[[redirects]]
  from = "/documentation"
  to = "/docs"
  status = 301

[[redirects]]
  from = "/concepts"
  to = "/docs"
  status = 301

[[redirects]]
  from = "/architecture"
  to = "/docs/architecture"
  status = 301

[[redirects]]
  from = "/setup"
  to = "/docs/setup"
  status = 301

[[redirects]]
  from = "/setup/local-with-vagrant"
  to = "/docs/setup/local-with-vagrant"
  status = 301

[[redirects]]
  from = "/setup/packet-with-terraform"
  to = "/docs/setup/packet-with-terraform"
  status = 301

[[redirects]]
  from = "/setup/packet-with-terraform/provisioner"
  to = "/docs/setup/packet-with-terraform/provisioner"
  status = 301

[[redirects]]
  from = "/setup/packet-with-terraform/hardware-data"
  to = "/docs/setup/packet-with-terraform/hardware-data"
  status = 301

[[redirects]]
  from = "/hardware-data"
  to = "/docs/hardware-data"
  status = 301

[[redirects]]
  from = "/templates"
  to = "/docs/templates"
  status = 301

[[redirects]]
  from = "/troubleshooting"
  to = "/docs/troubleshooting"
  status = 301

[[redirects]]
  from = "/cli-reference"
  to = "/cli"
  status = 301

[[redirects]]
  from = "/cli-reference/hardware"
  to = "/cli/hardware"
  status = 301

[[redirects]]
  from = "/cli-reference/template"
  to = "/cli/template"
  status = 301

[[redirects]]
  from = "/cli-reference/workflow"
  to = "/cli/workflow"
  status = 301

[[redirects]]
  from = "/contributors"
  to = "/community/contributors"
  status = 301

[[redirects]]
  from = "/community-slack"
  to = "/community/slack"
  status = 301

[[redirects]]
  from = "/support"
  to = "/community/support"
  status = 301

[[redirects]]
  from = "/license"
  to = "/terms/license"
  status = 301

[[redirects]]
  from = "/docs/setup/packet-with-terraform"
  to = "/docs/setup/terraform"
  status = 301

[[redirects]]
  from = "/setup/packet-with-terraform/provisioner"
  to = "/docs/setup/terraform/provisioner"
  status = 301

[[redirects]]
  from = "/setup/packet-with-terraform/hardware-data"
  to = "/docs/setup/terraform/hardware-data"
  status = 301

[[redirects]]
  from = "/cli"
  to = "/docs/cli"
  status = 301

[[redirects]]
  from = "/cli/hardware"
  to = "/docs/cli/hardware"
  status = 301

[[redirects]]
  from = "/cli/template"
  to = "/docs/cli/template"
  status = 301

[[redirects]]
  from = "/cli/workflow"
  to = "/docs/cli/workflow"
  status = 301

[[redirects]]
  from = "/docs/#whats-powering-tinkerbell"
  to = "https://docs.tinkerbell.org/#whats-powering-tinkerbell"
  status = 301

[[redirects]]
  from = "/docs"
  to = "https://docs.tinkerbell.org"
  status = 301

[[redirects]]
  from = "/docs/architecture"
  to = "https://docs.tinkerbell.org/about/architecture/"
  status = 301

[[redirects]]
  from = "/docs/setup/local-with-vagrant"
  to = "https://docs.tinkerbell.org/setup/local-vagrant/"
  status = 301

[[redirects]]
  from = "/docs/setup/packet-with-terraform"
  to = "https://docs.tinkerbell.org/setup/packet-terraform/"
  status = 301

[[redirects]]
  from = "/docs/setup/packet-with-terraform/provisioner"
  to = "https://docs.tinkerbell.org/setup/packet-terraform/#setting-up-the-provisioner"
  status = 301

[[redirects]]
  from = "/docs/hardware-data"
  to = "https://docs.tinkerbell.org/about/hardware-data/"
  status = 301

[[redirects]]
  from = "/docs/templates"
  to = "https://docs.tinkerbell.org/about/templates/"
  status = 301

[[redirects]]
  from = "/docs/troubleshooting"
  to = "https://docs.tinkerbell.org/troubleshooting/"
  status = 301

[[redirects]]
  from = "/docs/setup/terraform"
  to = "https://docs.tinkerbell.org/setup/packet-terraform/"
  status = 301

[[redirects]]
  from = "/docs/setup/terraform/provisioner"
  to = "https://docs.tinkerbell.org/setup/packet-terraform/#setting-up-the-provisioner"
  status = 301

[[redirects]]
  from = "/docs/cli"
  to = "https://docs.tinkerbell.org/cli-reference/hardware/"
  status = 301

[[redirects]]
  from = "/docs/cli/hardware"
  to = "https://docs.tinkerbell.org/cli-reference/hardware/"
  status = 301

[[redirects]]
  from = "/docs/cli/template"
  to = "https://docs.tinkerbell.org/cli-reference/template/"
  status = 301

[[redirects]]
  from = "/docs/cli/workflow"
  to = "https://docs.tinkerbell.org/cli-reference/workflow/"
  status = 301
